From: Matthias Klose <doko@ubuntu.com>
Date: Thu, 7 Mar 2019 17:49:54 +0100
Subject: skip some tests that fail with py 3.7

Bug: https://github.com/celery/celery/issues/4913
---
 t/unit/worker/test_loops.py | 4 +++-
 1 file changed, 3 insertions(+), 1 deletion(-)

diff --git a/t/unit/worker/test_loops.py b/t/unit/worker/test_loops.py
index 5c96175..b0a323c 100644
--- a/t/unit/worker/test_loops.py
+++ b/t/unit/worker/test_loops.py
@@ -4,7 +4,7 @@ import errno
 import socket
 
 import pytest
-from case import Mock
+from case import Mock, skip
 from kombu.asynchronous import ERR, READ, WRITE, Hub
 
 from celery.bootsteps import CLOSE, RUN
@@ -368,6 +368,7 @@ class test_asynloop:
         assert gen.gi_frame.f_lasti != -1
         x.hub.remove.assert_not_called()
 
+    @skip.if_python3(reason='Python 3.7: https://github.com/celery/celery/issues/4913')
     def test_poll_write_generator_stopped(self):
         x = X(self.app)
 
@@ -411,6 +412,7 @@ class test_asynloop:
         reader.assert_called_with(6, 24)
         poller.poll.assert_called()
 
+    @skip.if_python3(reason='Python 3.7: https://github.com/celery/celery/issues/4913')
     def test_poll_raises_ValueError(self):
         x = X(self.app)
         x.hub.readers = {6: Mock()}
